"""
install_git_hook.py
===================
Installs a post-commit git hook that runs the intelligent-doc-engine pipeline.

Usage:
    python scripts/install_git_hook.py
"""

from __future__ import annotations

import sys
from pathlib import Path


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    git_dir = project_root / ".git"
    hooks_dir = git_dir / "hooks"

    if not git_dir.exists() or not git_dir.is_dir():
        print(f"No .git directory found at {git_dir}. Run this inside a git repository.")
        sys.exit(1)

    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "post-commit"

    # Git hooks are executed by sh, so use POSIX-style slashes.
    project_root_posix = project_root.as_posix()
    hook_content = (
        "#!/bin/sh\n"
        "# Auto-generated by intelligent-doc-engine/scripts/install_git_hook.py\n"
        f"cd \"{project_root_posix}\" || exit 0\n"
        "python -m src.runner || echo \"[intelligent-doc-engine] post-commit run failed\"\n"
    )

    hook_path.write_text(hook_content, encoding="utf-8")

    try:
        hook_path.chmod(0o755)
    except OSError:
        # On Windows this may not be necessary, but keep best effort.
        pass

    print(f"Installed git post-commit hook: {hook_path}")


if __name__ == "__main__":
    main()
