"""
analytics_docx_writer.py
========================
Converts the Markdown output from analytics_doc_generator into a formatted
Word (.docx) document with embedded architecture/lineage diagram PNGs.

Reuses:
  - src/mermaid_renderer.py  — renders Mermaid code to PNG (mmdc or mermaid.ink)
  - python-docx              — builds the Word document
"""
from __future__ import annotations

import re
import tempfile
import logging
from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from .mermaid_renderer import extract_mermaid_code, render_mermaid_to_png, render_mermaid_to_png_with_fallback

logger = logging.getLogger(__name__)

_MERMAID_BLOCK_RE = re.compile(r"```mermaid\s*\n(.*?)```", re.DOTALL)
_TABLE_RE = re.compile(r"(\|.+\|(\n|$))+")


def write_docx(markdown: str, output_path: str, title: str = "Analytics Documentation") -> Path:
    """Convert *markdown* to a Word document at *output_path*.

    Mermaid diagrams are rendered to PNG and embedded as images.
    Pipe-delimited tables are converted to Word tables.
    Headings, bullets, and code blocks are styled appropriately.

    Returns the resolved output path.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    doc = Document()
    _set_default_style(doc)

    # Render all Mermaid blocks to temp PNGs — replace ALL blocks regardless of outcome
    # so raw Mermaid syntax never appears in the output document.
    block_replacements: dict[str, str] = {}
    for i, m in enumerate(_MERMAID_BLOCK_RE.finditer(markdown)):
        mermaid_code = m.group(1).strip()
        png_path = str(Path(tempfile.gettempdir()) / f"analytics_diagram_{i}.png")
        result = render_mermaid_to_png(mermaid_code, png_path)
        if result:
            block_replacements[m.group(0)] = f"[[DIAGRAM:{png_path}]]"
            logger.info("Rendered diagram %d → %s", i, result)
        else:
            # Rendering failed — insert a clean placeholder instead of raw text
            block_replacements[m.group(0)] = "[[DIAGRAM_FAILED]]"
            logger.warning("Diagram %d could not be rendered", i)

    processed = markdown
    for raw_block, replacement in block_replacements.items():
        processed = processed.replace(raw_block, replacement)

    # ── Cover page ─────────────────────────────────────────────────────────
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

    sub = doc.add_paragraph(
        f"Generated by Intelligent Doc Engine  ·  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in sub.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    doc.add_page_break()

    # ── Body ───────────────────────────────────────────────────────────────
    lines = processed.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Heading 1  (#)
        if line.startswith("# ") and not line.startswith("## "):
            h = doc.add_heading(line[2:].strip(), level=1)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
            i += 1
            continue

        # Heading 2 (##)
        if line.startswith("## "):
            h = doc.add_heading(line[3:].strip(), level=2)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x2E, 0x74, 0xB5)
            i += 1
            continue

        # Heading 3 (###)
        if line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=3)
            i += 1
            continue

        # Embedded diagram placeholder — rendered PNG
        if line.startswith("[[DIAGRAM:") and line.endswith("]]"):
            png_path = line[10:-2]
            if Path(png_path).exists():
                para = doc.add_paragraph()
                para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = para.add_run()
                run.add_picture(png_path, width=Inches(_fit_width(png_path)))
                doc.add_paragraph()
            else:
                para = doc.add_paragraph("[Diagram image not available]")
                para.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)
            i += 1
            continue

        # Embedded diagram placeholder — render failed
        if line == "[[DIAGRAM_FAILED]]":
            para = doc.add_paragraph(
                "Lineage diagram could not be rendered. "
                "Install mermaid-cli (npm install -g @mermaid-js/mermaid-cli) for offline rendering."
            )
            para.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)
            para.runs[0].font.italic = True
            i += 1
            continue

        # Pipe table — collect all table lines
        if "|" in line and line.strip().startswith("|"):
            table_lines = []
            while i < len(lines) and "|" in lines[i] and lines[i].strip().startswith("|"):
                table_lines.append(lines[i])
                i += 1
            _write_table(doc, table_lines)
            continue

        # Bullet point
        if line.startswith("- ") or line.startswith("* "):
            para = doc.add_paragraph(line[2:].strip(), style="List Bullet")
            para.runs[0].font.size = Pt(10)
            i += 1
            continue

        # Numbered list
        if re.match(r"^\d+\.\s", line):
            para = doc.add_paragraph(re.sub(r"^\d+\.\s", "", line).strip(), style="List Number")
            para.runs[0].font.size = Pt(10)
            i += 1
            continue

        # Code block (non-mermaid)
        if line.startswith("```"):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            if code_lines:
                para = doc.add_paragraph("\n".join(code_lines))
                para.runs[0].font.name = "Courier New"
                para.runs[0].font.size = Pt(8)
            continue

        # Bold inline (**text**)
        if "**" in line:
            _write_inline_bold(doc, line)
            i += 1
            continue

        # Horizontal rule
        if line.strip() in ("---", "***", "___"):
            doc.add_paragraph("─" * 60)
            i += 1
            continue

        # Regular paragraph (skip blank lines)
        if line.strip():
            para = doc.add_paragraph(line.strip())
            para.runs[0].font.size = Pt(10)

        i += 1

    doc.save(str(out))
    logger.info("Word document written to %s", out)
    return out.resolve()


# ── Helpers ──────────────────────────────────────────────────────────────────

def _set_default_style(doc: Document) -> None:
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(10)


def _write_table(doc: Document, table_lines: list[str]) -> None:
    def split_row(line: str) -> list[str]:
        cells = [c.strip() for c in line.split("|")]
        return [c for c in cells if c]

    # Filter separator rows (---|--- pattern)
    data_lines = [
        ln for ln in table_lines
        if not re.match(r"^\s*\|?\s*[-:]+\s*(\|\s*[-:]+\s*)*\|?\s*$", ln)
    ]
    if len(data_lines) < 1:
        return

    headers = split_row(data_lines[0])
    rows = [split_row(ln) for ln in data_lines[1:]]

    if not headers:
        return

    num_cols = len(headers)
    table = doc.add_table(rows=1 + len(rows), cols=num_cols)
    table.style = "Table Grid"

    for ci, h in enumerate(headers):
        cell = table.rows[0].cells[ci]
        cell.text = h
        for run in cell.paragraphs[0].runs:
            run.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        # Header cell background (dark blue)
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), "1F497D")
        tcPr.append(shd)

    for ri, row in enumerate(rows):
        for ci, val in enumerate(row[:num_cols]):
            cell = table.rows[ri + 1].cells[ci]
            cell.text = val
            for run in cell.paragraphs[0].runs:
                run.font.size = Pt(9)

    doc.add_paragraph()  # spacing after table


def _fit_width(
    png_path: str,
    max_width_in: float = 6.0,
    max_height_in: float = 4.0,
) -> float:
    """Return an embed width (inches) that keeps the image within max_width × max_height.

    Reads only the PNG IHDR chunk — no Pillow needed.
    Preserves aspect ratio and never upscales small images.
    """
    import struct
    try:
        with open(png_path, "rb") as f:
            f.read(8)   # PNG signature
            f.read(4)   # IHDR chunk length
            f.read(4)   # "IHDR" type
            width_px  = struct.unpack(">I", f.read(4))[0]
            height_px = struct.unpack(">I", f.read(4))[0]
        dpi = 96  # mmdc default rendering DPI
        nat_w = width_px  / dpi
        nat_h = height_px / dpi
        # Scale factor that keeps the image inside the max_width × max_height box
        scale = min(1.0, max_width_in / nat_w, max_height_in / nat_h)
        embed_w = nat_w * scale
        # Only apply a floor when doing so doesn't push height back over the limit
        if embed_w < 1.5 and (1.5 / nat_w) * nat_h <= max_height_in:
            embed_w = 1.5
        return embed_w
    except Exception:
        return max_width_in  # safe fallback


def _write_inline_bold(doc: Document, line: str) -> None:
    para = doc.add_paragraph()
    parts = re.split(r"\*\*", line)
    for idx, part in enumerate(parts):
        if not part:
            continue
        run = para.add_run(part)
        run.bold = (idx % 2 == 1)
        run.font.size = Pt(10)
