"""Generate Markdown documentation using Claude for SQL, ADF, and Azure Function artefacts."""
from __future__ import annotations
import json
import os
import shutil
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .parsers.sql_parser import SQLFileInfo
from .parsers.adf_parser import ADFPipelineInfo, ADFDatasetInfo, ADFLinkedServiceInfo
from .parsers.function_parser import FunctionInfo
from .lineage import LineageGraph
from .adf_lineage_builder import detect_and_build as _build_adf_lineage


MODEL = os.getenv("ANALYTICS_DOC_MODEL", "claude-sonnet-4-6")
MAX_TOKENS = 2048
_BLUEPRINT_MAX_TOKENS = 8192   # SQL blueprint output is much larger than other sections
_CLI_TIMEOUT = 300

# ── SQL blueprint system prompt ───────────────────────────────────────────────

_SQL_BLUEPRINT_SYSTEM_PROMPT = """\
You are an expert Data Architect and Technical Writer specializing in Snowflake SQL, dbt pipelines, \
and modern analytics engineering. Your task is to analyze raw database schemas, SQL statements, and \
file change lists, and synthesize them into a highly readable, noise-reduced pipeline documentation file.

You will receive two input variables:
1. <repo_metadata>: A JSON-structured dictionary containing the parsed database objects, column \
linkages, load strategies, and code modifications.
2. <execution_scope>: String indicating whether the run is "PR Changes Only" or a "Full Repository" scan.

Your output must be structured, clean Markdown. Strictly enforce all four rules below.

### MANDATORY READABILITY RULES

1. COLLAPSIBLE MEDALLION DIRECTORIES — wrap each layer catalog in an HTML details block:
   <details>
   <summary><b>📂 View {Layer Name} Layer Catalog ({Count} Objects)</b></summary>
   ... content ...
   </details>

2. AGGREGATE 1:1 PASS-THROUGH COLUMNS — do NOT generate table rows for columns whose \
source_column matches target_column with no transformation. Summarise with a block quote instead:
   > 🔄 **Direct Pass-Through Columns (Unchanged):** col_a, col_b, col_c ... ({Count} total)
   Build explicit column tables ONLY for Primary/Foreign Keys and columns with real transformations \
(COALESCE, CASE WHEN, window functions, computed expressions, renames).

3. NO REPETITIVE ERROR DIAGNOSTICS — if a diagram or element cannot be rendered, show a clean \
nested bullet hierarchy of parent → child table relationships instead of repeating error text.

4. COMPLEX SQL EXTRACTION — in the "Extracted Complex SQL Logic" section, include ONLY files that \
contain CTEs, window functions, regex, or business calculation logic. Do not dump basic SELECT files.

### REQUIRED OUTPUT STRUCTURE

# 📊 Data Pipeline Blueprint & Impact Analysis
`Generated by Auto-Doc Engine` | `Scope: {execution_scope}` | `Execution Date: {current_date}`

---

## 🧭 Executive Dashboard & Metrics
{2–3 sentence executive analysis: what this pipeline run or PR accomplishes, which layers are \
touched, and any high-risk / breaking objects.}

### 📈 Pipeline Health & Structural Summary
| Metric | Count | Changed / Affected | Key Details / Coverage |
| :--- | :--- | :--- | :--- |
| **📁 SQL pipeline files** | `{total_sql_files}` | `{changed_sql_files}` | `{parsing_health_pct}% successfully parsed` |
| **🗃️ DB Objects Managed** | `{total_objects}` | `{changed_objects}` | `{table_count} Tables \| {view_count} Views \| {pipe_count} Pipes` |
| **⚡ Medallion Flow** | `{layers_discovered_count}` | `{changed_layers_count}` | Data Flow: `{layer_sequence_flow_string}` |

### 🔍 Quick Jump: Medallion Layers
* 🗄️ [**RAW Layer**](#raw-layer-ingestion--landing-zone) — Ingestion tables, bulk loads, and staging pipes.
* 🥈 [**SILVER Layer**](#silver-layer-conformed--cleaned) — Cleansed, normalised historical dimensions.
* 🥇 [**GOLD/MART Layer**](#gold--mart-layers-analytical-dimensions--aggregated-facts) — Aggregated facts and dashboard-ready marts.

---

## 🚀 Pipeline Object Execution Matrix
| Medallion Layer | Object Name | Object Type | Load Strategy | Primary Key | Complexity | Schema Status |
| :--- | :--- | :--- | :--- | :--- | :---: | :---: |
{one row per object from objects[]}

---

## 🗂️ Detailed Schema & Lineage Directory

### 🗄️ RAW Layer (Ingestion & Landing Zone)
<details><summary><b>📂 View RAW Layer Catalog ({count} Objects)</b></summary><br/>
{for each RAW object: heading, load strategy, source path, full column table}
</details>

### 🥈 SILVER Layer (Conformed & Cleaned)
<details><summary><b>🥈 View SILVER Layer Catalog ({count} Objects)</b></summary><br/>
{for each SILVER object: heading, description, load strategy, upstream sources, pass-through block \
quote, transformation table for non-trivial columns only}
</details>

### 🥇 GOLD & MART Layers (Analytical Dimensions & Aggregated Facts)
<details><summary><b>🥇 View GOLD & MART Layer Catalog ({count} Objects)</b></summary><br/>
{same structure as SILVER}
</details>

---

## 🧪 Extracted Complex SQL Logic & Window Expressions
{One subsection per entry in complex_sql_extracts[]. Include the sql_code_snippet in a sql fenced \
block, then bullet the explained_rules as "Core Analytical Heuristics".}

---

## 🔑 Primary Key & Structural Constraints Directory
| Layer | Object Name | Primary Key Columns | Surrogate Key Strategy | Validation Test |
| :--- | :--- | :--- | :--- | :--- |
{one row per object that has primary_keys[]}

---
_Generated by Intelligent Doc Engine — Claude-powered blueprint_
"""


def _read_claude_oauth_token() -> Optional[str]:
    """Read a non-expired OAuth access token from ~/.claude/.credentials.json."""
    try:
        creds_path = Path.home() / ".claude" / ".credentials.json"
        if not creds_path.exists():
            return None
        creds = json.loads(creds_path.read_text(encoding="utf-8"))
        # Support both known key names for the OAuth block
        oauth = creds.get("claudeAiOauth") or creds.get("claudeAiOauthTokens") or {}
        token = oauth.get("accessToken")
        if not token:
            return None
        expires_at = oauth.get("expiresAt")
        if isinstance(expires_at, (int, float)) and expires_at / 1000 < time.time():
            return None  # Token has expired
        return token
    except Exception:
        return None


def _call_claude(system_prompt: str, user_prompt: str, max_tokens: int = MAX_TOKENS) -> str:
    """Call Claude via API key, Claude.ai OAuth token, or claude CLI (in that order)."""
    import anthropic

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if api_key:
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=MODEL,
            max_tokens=max_tokens,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        return resp.content[0].text

    # Try Claude.ai OAuth token from credentials.json (written by setup-doc-engine action)
    oauth_token = _read_claude_oauth_token()
    if oauth_token:
        try:
            client = anthropic.Anthropic(auth_token=oauth_token)
            resp = client.messages.create(
                model=MODEL,
                max_tokens=max_tokens,
                system=system_prompt,
                messages=[{"role": "user", "content": user_prompt}],
            )
            return resp.content[0].text
        except Exception:
            pass  # Fall through to CLI

    # Last resort: claude CLI subprocess
    cli = shutil.which("claude")
    if not cli:
        raise RuntimeError(
            "Claude authentication failed. Set one of:\n"
            "  ANTHROPIC_API_KEY — API key from console.anthropic.com\n"
            "  CLAUDE_CREDENTIALS — base64 of ~/.claude/.credentials.json (re-encode if expired)"
        )
    combined = f"<system>\n{system_prompt}\n</system>\n\n{user_prompt}"
    result = subprocess.run(
        [cli, "-p", "--model", MODEL],
        input=combined,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=_CLI_TIMEOUT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"claude CLI exited {result.returncode}: {result.stderr.strip() or result.stdout.strip()}\n"
            "Tip: CLAUDE_CREDENTIALS OAuth tokens expire. Re-encode ~/.claude/.credentials.json "
            "or switch to ANTHROPIC_API_KEY."
        )
    return result.stdout.strip()


def _build_repo_metadata(
    sql_files: list[SQLFileInfo],
    scope: str,
    total_sql_files: Optional[int] = None,
) -> dict:
    """Convert parsed SQLFileInfo objects into the repo_metadata JSON schema for the blueprint prompt.

    Args:
        sql_files:        Parsed SQL file objects (the changed or full-repo set).
        scope:            Human-readable scope string passed to the prompt.
        total_sql_files:  Total files in the repo (may be larger than len(sql_files) for PR scans).

    Returns:
        Dict matching the repo_metadata JSON schema expected by _SQL_BLUEPRINT_SYSTEM_PROMPT.
    """
    total = total_sql_files or len(sql_files)
    parsed_ok = sum(1 for f in sql_files if f.primary_target or f.object_name)
    parsing_health = int(100 * parsed_ok / max(1, total))

    layer_order = ["raw", "stage", "silver", "mart", "gold"]
    layers_present = {f.layer for f in sql_files if f.layer and f.layer != "unknown"}
    layer_seq = " ➔ ".join(l.upper() for l in layer_order if l in layers_present) or "Unknown"

    table_count = sum(1 for f in sql_files if f.object_type == "TABLE")
    view_count  = sum(1 for f in sql_files if f.object_type == "VIEW")
    pipe_count  = sum(1 for f in sql_files if f.object_type == "PIPE")

    objects: list[dict] = []
    complex_extracts: list[dict] = []

    for f in sql_files:
        obj_name = str(f.primary_target) if f.primary_target else (f.object_name or "UNKNOWN")
        pk_set   = {c.upper() for c in (f.pk_columns or [])}
        lineage  = f.column_lineage or []

        # Split column lineage into pass-through vs transformed
        pass_through: list[str] = []
        transformed:  list[dict] = []

        if lineage:
            for m in lineage:
                col = m.target_col
                if not col or col in ("*", "(expression)"):
                    continue
                is_passthrough = (
                    m.source_col is not None
                    and m.source_col.upper() == col.upper()
                )
                if is_passthrough:
                    pass_through.append(col)
                else:
                    transformed.append({
                        "name": col,
                        "type": "",
                        "is_pk": col.upper() in pk_set,
                        "source_table": m.source_table or "",
                        "source_column": m.source_col or "",
                        "transformation": (
                            "(computed expression — see source SQL)"
                            if m.source_col is None
                            else f"renamed from {m.source_col}"
                        ),
                    })
        else:
            # No lineage data available — treat all parsed columns as pass-through
            pass_through = list(f.columns)

        # Complexity: High if ≥2 CTEs or ≥4 sources or ≥3 expression columns
        expr_count = sum(1 for t in transformed if not t["source_column"])
        cte_count  = len(f.ctes or [])
        src_count  = len(f.sources or [])
        if cte_count >= 2 or src_count >= 4 or expr_count >= 3:
            complexity = "High"
        elif cte_count >= 1 or src_count >= 2 or expr_count >= 1:
            complexity = "Medium"
        else:
            complexity = "Low"

        objects.append({
            "name": obj_name,
            "layer": (f.layer or "unknown").upper(),
            "object_type": f.object_type or "UNKNOWN",
            "load_strategy": f.load_strategy or "UNKNOWN",
            "primary_keys": f.pk_columns or [],
            "complexity": complexity,
            "status": "Modified",
            "description": "",
            "upstream_sources": [str(s) for s in (f.sources or [])],
            "schema": {
                "pass_through_columns": pass_through,
                "transformed_columns": transformed,
            },
        })

        # Collect complex SQL snippets for files that contain CTEs
        if f.ctes and f.raw_sql:
            raw_lines = f.raw_sql.splitlines()
            snippet = "\n".join(raw_lines[:40])
            if len(raw_lines) > 40:
                snippet += "\n..."
            complex_extracts.append({
                "sql_file_path": f.path.replace("\\", "/"),
                "target_table": obj_name,
                "ctes_detected": f.ctes,
                "sql_code_snippet": snippet,
                "explained_rules": [
                    {
                        "logic_element": f"CTE: {cte}",
                        "explanation": (
                            f"Common table expression '{cte}' pre-processes an intermediate "
                            f"dataset consumed by '{obj_name}'."
                        ),
                    }
                    for cte in f.ctes[:5]
                ],
            })

    return {
        "execution_metadata": {
            "scope": scope,
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "total_sql_files": total,
            "changed_sql_files": len(sql_files),
            "parsing_health_pct": parsing_health,
        },
        "metrics": {
            "total_objects": len(sql_files),
            "changed_objects": len(sql_files),
            "table_count": table_count,
            "view_count": view_count,
            "pipe_count": pipe_count,
            "layers_discovered_count": len(layers_present),
            "changed_layers_count": len(layers_present),
            "layer_sequence_flow_string": layer_seq,
        },
        "objects": objects,
        "complex_sql_extracts": complex_extracts,
    }


def document_sql_pr(
    changed_files: list[SQLFileInfo],
    pr_title: str,
    pr_description: str,
    graph: Optional[LineageGraph] = None,
) -> str:
    """Generate a Data Pipeline Blueprint from parsed SQL files using Claude.

    Builds a structured repo_metadata JSON payload from the parsed SQLFileInfo
    objects and calls Claude with the blueprint system prompt, which produces
    a medallion-layered, noise-reduced, collapsible Markdown document.

    Args:
        changed_files:  Parsed SQL file objects (PR-changed or full-repo set).
        pr_title:       PR title used as document context.
        pr_description: PR description (empty string for directory scans).
        graph:          Optional lineage graph — mermaid diagrams are appended
                        after the Claude-generated blueprint.

    Returns:
        Structured Markdown blueprint string.
    """
    scope = "PR Changes Only" if pr_description else "Full Repository"
    repo_metadata = _build_repo_metadata(changed_files, scope)

    user_prompt = (
        f"<repo_metadata>\n"
        f"{json.dumps(repo_metadata, indent=2, ensure_ascii=False)}\n"
        f"</repo_metadata>\n\n"
        f"<execution_scope>{scope}</execution_scope>\n\n"
        f"<pr_context>\n"
        f"Title: {pr_title}\n"
        + (f"Description: {pr_description}\n" if pr_description else "")
        + "</pr_context>"
    )

    blueprint = _call_claude(
        system_prompt=_SQL_BLUEPRINT_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        max_tokens=_BLUEPRINT_MAX_TOKENS,
    )

    # Append Mermaid lineage diagrams — rendered to PNG by write_docx / write_html
    if graph and graph.edges:
        diagrams = graph.to_layer_diagrams(title_prefix=f"Lineage — {pr_title}")
        diagram_blocks = "\n\n".join(mermaid for _, mermaid in diagrams)
        blueprint += f"\n\n---\n\n## 📐 Data Lineage Diagrams\n\n{diagram_blocks}\n"

    return blueprint


def document_adf_pr(
    pipelines: list[ADFPipelineInfo],
    datasets: list[ADFDatasetInfo],
    linked_services: list[ADFLinkedServiceInfo],
    pr_title: str,
    pr_description: str,
) -> str:
    pipeline_details = "\n\n".join(_adf_pipeline_detail(p) for p in pipelines[:10])
    dataset_list = "\n".join(
        f"- `{d.name}` ({d.dataset_type}, linked: `{d.linked_service}`)" for d in datasets
    )
    ls_list = "\n".join(f"- `{ls.name}` ({ls.service_type})" for ls in linked_services)

    user_prompt = f"""Generate documentation for this Azure Data Factory pull request.

**PR Title:** {pr_title}
**PR Description:** {pr_description or "(none provided)"}

**Pipelines Changed:**
{pipeline_details or "(none)"}

**Datasets Changed:**
{dataset_list or "(none)"}

**Linked Services Changed:**
{ls_list or "(none)"}

Write the following sections:
1. **Overview** – what this PR does and why
2. **Pipeline Changes** – for each pipeline, describe activities, control flow, and data movement
3. **Activity Flow Diagram** – embed a Mermaid flowchart for each pipeline showing activity dependencies
4. **Dataset & Connection Changes** – describe any schema or connection changes
5. **Operational Notes** – triggers, schedules, retry policies, monitoring considerations
"""
    ai_doc = _call_claude(
        system_prompt=(
            "You are a senior Azure Data Factory engineer writing technical documentation. "
            "Use Markdown. Include Mermaid diagrams for activity flows."
        ),
        user_prompt=user_prompt,
    )

    static_diagrams = "\n\n".join(
        _pipeline_mermaid(p) for p in pipelines if p.activity_flow
    )
    if static_diagrams:
        ai_doc += f"\n\n## Activity Flow Diagrams (Auto-generated)\n\n{static_diagrams}"

    # End-to-end data lineage — auto-detected from datasets + linked services
    lineage_section = ""
    lineage = _build_adf_lineage(pipelines, datasets, linked_services)
    if lineage.can_build:
        source_note = (
            f"{lineage.source_count} source system(s), "
            if lineage.source_count else ""
        )
        lineage_section = (
            f"\n\n## End-to-End Data Lineage\n\n"
            f"> Auto-generated from {lineage.pipeline_count} pipeline(s) "
            f"({source_note}spanning all storage layers).\n\n"
            f"{lineage.mermaid_code}\n"
        )

    return f"""# PR Documentation: {pr_title}

{ai_doc}
{lineage_section}
---
_Generated by Intelligent Doc Engine | Model: {MODEL}_
"""


def document_function_pr(
    functions: list[FunctionInfo],
    pr_title: str,
    pr_description: str,
) -> str:
    func_details = "\n\n".join(_function_detail(f) for f in functions[:10])

    user_prompt = f"""Generate documentation for this Azure Functions pull request.

**PR Title:** {pr_title}
**PR Description:** {pr_description or "(none provided)"}

**Functions Changed:**
{func_details or "(none)"}

Write the following sections:
1. **Overview** – purpose and impact of this PR
2. **Function Changes** – for each function: purpose, trigger, input/output bindings, key logic
3. **API / Event Contract** – HTTP routes, event schemas, queue names, blob paths
4. **Error Handling & Retry** – any error handling or retry logic added/modified
5. **Dependencies** – external services, environment variables, connection strings referenced
"""
    ai_doc = _call_claude(
        system_prompt=(
            "You are a senior Azure Functions engineer writing technical documentation. "
            "Use Markdown. Be precise about triggers and bindings."
        ),
        user_prompt=user_prompt,
    )

    return f"""# PR Documentation: {pr_title}

{ai_doc}

---
_Generated by Intelligent Doc Engine | Model: {MODEL}_
"""


def document_generic_pr(diff: str, pr_title: str, pr_description: str) -> str:
    text = _call_claude(
        system_prompt="You are a technical writer. Generate Markdown documentation from a PR diff.",
        user_prompt=(
            f"PR Title: {pr_title}\nDescription: {pr_description}\n\nDiff:\n{diff[:4000]}\n\n"
            "Write: Overview, Changes Made, Impact, Notes."
        ),
    )
    return (
        f"# PR Documentation: {pr_title}\n\n"
        f"{text}\n\n"
        f"---\n_Generated by Intelligent Doc Engine_\n"
    )


# ── Helpers ──────────────────────────────────────────────────────────────────

def _sql_file_table(files: list[SQLFileInfo]) -> str:
    rows = ["| File | Layer | Type | Object | Strategy |", "|---|---|---|---|---|"]
    for f in files:
        fname = f.path.replace("\\", "/").split("/")[-1]
        rows.append(
            f"| `{fname}` | {f.layer} | {f.object_type} | `{f.object_name}` | {f.load_strategy} |"
        )
    return "\n".join(rows)


def _column_lineage_section(files: list[SQLFileInfo]) -> str:
    """Build a Markdown column lineage section for files that have column mapping data."""
    sections = []
    for f in files:
        if not f.column_lineage:
            continue
        fname = f.path.replace("\\", "/").split("/")[-1]
        target = str(f.primary_target) if f.primary_target else f.object_name or fname

        rows = ["| Target Column | Source Table | Source Column |", "|---|---|---|"]
        for m in f.column_lineage:
            src_tbl = f"`{m.source_table}`" if m.source_table else "—"
            src_col = f"`{m.source_col}`" if m.source_col else "_(expression)_"
            rows.append(f"| `{m.target_col}` | {src_tbl} | {src_col} |")

        sections.append(f"### `{fname}` → `{target}`\n\n" + "\n".join(rows))

    if not sections:
        return ""
    return "\n## Column Lineage\n\n" + "\n\n".join(sections) + "\n"


def _sql_file_detail(f: SQLFileInfo) -> str:
    targets = ", ".join(f"`{t}`" for t in f.targets) or "_none_"
    sources = ", ".join(f"`{s}`" for s in f.sources[:10]) or "_none_"
    ctes    = ", ".join(f"`{c}`" for c in f.ctes) or "_none_"
    cols    = ", ".join(f"`{c}`" for c in f.columns[:15]) or "_not parsed_"
    fname   = f.path.replace("\\", "/").split("/")[-1]

    snippet = ""
    if f.raw_sql:
        first_lines = "\n".join(f.raw_sql.splitlines()[:30])
        snippet = f"\n```sql\n{first_lines}\n...\n```"

    return f"""### `{fname}`
- **Layer:** {f.layer} | **Type:** {f.object_type} | **Strategy:** {f.load_strategy}
- **Targets:** {targets}
- **Sources:** {sources}
- **CTEs:** {ctes}
- **Columns:** {cols}
{snippet}"""


def _adf_pipeline_detail(p: ADFPipelineInfo) -> str:
    acts = "\n".join(
        f"  - `{a.name}` ({a.activity_type})"
        + (f" → depends on: {a.depends_on}" if a.depends_on else "")
        + (f" | in: {a.inputs}" if a.inputs else "")
        + (f" | out: {a.outputs}" if a.outputs else "")
        for a in p.activities
    )
    return f"""### Pipeline: `{p.name}`
- **Description:** {p.description or "(none)"}
- **Parameters:** {', '.join(p.parameters) or "(none)"}
- **Variables:** {', '.join(p.variables) or "(none)"}
- **Activities ({len(p.activities)}):**
{acts}"""


def _pipeline_mermaid(p: ADFPipelineInfo) -> str:
    if not p.activities:
        return ""
    lines = [f"#### `{p.name}` Activity Flow", "", "```mermaid", "flowchart TD"]
    node_ids = {a.name: f"a{i}" for i, a in enumerate(p.activities)}
    for a in p.activities:
        nid = node_ids[a.name]
        lines.append(f'    {nid}["{a.name}\\n({a.activity_type})"]')
    for src, tgt in p.activity_flow:
        src_id = node_ids.get(src, "")
        tgt_id = node_ids.get(tgt, "")
        if src_id and tgt_id:
            lines.append(f"    {src_id} --> {tgt_id}")
    lines.append("```")
    return "\n".join(lines)


def _function_detail(f: FunctionInfo) -> str:
    bindings_str = "\n".join(
        f"  - `{b.name}` — {b.binding_type} ({b.direction})" for b in f.bindings
    ) or "  (none)"
    http_str = ", ".join(f.http_methods) if f.http_methods else ""
    route_str = f"`{f.route}`" if f.route else ""
    schedule_str = f"`{f.trigger_schedule}`" if f.trigger_schedule else ""
    return f"""### Function: `{f.function_name}` ({f.language})
- **Trigger:** {f.trigger_type} {schedule_str or http_str or ""}
- **Route:** {route_str or "(N/A)"}
- **Auth Level:** {f.auth_level or "(N/A)"}
- **Description:** {f.description or "(none)"}
- **Bindings:**
{bindings_str}"""
