"""Generate Markdown documentation using Claude for SQL, ADF, and Azure Function artefacts."""
from __future__ import annotations
import os
import shutil
import subprocess
from typing import Optional

from .parsers.sql_parser import SQLFileInfo
from .parsers.adf_parser import ADFPipelineInfo, ADFDatasetInfo, ADFLinkedServiceInfo
from .parsers.function_parser import FunctionInfo
from .lineage import LineageGraph
from .adf_lineage_builder import detect_and_build as _build_adf_lineage


MODEL = os.getenv("ANALYTICS_DOC_MODEL", "claude-sonnet-4-6")
MAX_TOKENS = 2048
_CLI_TIMEOUT = 300


def _call_claude(system_prompt: str, user_prompt: str) -> str:
    """Call Claude via API key if available, otherwise fall back to `claude -p` CLI."""
    api_key = os.getenv("ANTHROPIC_API_KEY")

    if api_key:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        return resp.content[0].text

    # Fall back to claude CLI (Claude.ai subscription — no API key required)
    cli = shutil.which("claude")
    if not cli:
        raise RuntimeError(
            "No ANTHROPIC_API_KEY set and 'claude' CLI not found on PATH.\n"
            "Either set ANTHROPIC_API_KEY or install Claude Code: https://claude.ai/code"
        )
    combined = f"<system>\n{system_prompt}\n</system>\n\n{user_prompt}"
    result = subprocess.run(
        [cli, "-p", "--model", MODEL],
        input=combined,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=_CLI_TIMEOUT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"claude CLI exited {result.returncode}: {result.stderr.strip() or result.stdout.strip()}"
        )
    return result.stdout.strip()


def document_sql_pr(
    changed_files: list[SQLFileInfo],
    pr_title: str,
    pr_description: str,
    graph: Optional[LineageGraph] = None,
) -> str:
    file_summaries = _sql_file_table(changed_files)
    lineage_section = ""
    if graph and graph.edges:
        diagrams = graph.to_layer_diagrams(title_prefix=f"Lineage — {pr_title}")
        diagram_blocks = "\n\n".join(mermaid for _, mermaid in diagrams)
        lineage_section = f"\n## Data Lineage\n\n{diagram_blocks}\n"

    files_detail = "\n\n".join(_sql_file_detail(f) for f in changed_files[:15])

    user_prompt = f"""Generate documentation for this Snowflake/SQL pull request.

**PR Title:** {pr_title}
**PR Description:** {pr_description or "(none provided)"}

**Changed Files Summary:**
{file_summaries}

**File Details:**
{files_detail}

Write the following sections:
1. **Overview** – 2-3 sentence summary of the PR purpose
2. **Changes by Layer** – group files by RAW / SILVER / GOLD and describe each change
3. **Transformation Logic** – for each MERGE/INSERT/CREATE, explain the business logic
4. **Impact & Dependencies** – which downstream tables/views are affected
5. **Data Quality Notes** – any filters, deduplication, or validation logic added
"""
    ai_doc = _call_claude(
        system_prompt=(
            "You are a senior data engineer writing precise, technical documentation. "
            "Use Markdown. Be concise but complete. "
            "Focus on data transformations, business logic, and impact on downstream consumers."
        ),
        user_prompt=user_prompt,
    )

    column_lineage_section = _column_lineage_section(changed_files)

    return f"""# PR Documentation: {pr_title}

{ai_doc}
{lineage_section}{column_lineage_section}
---
_Generated by Intelligent Doc Engine | Model: {MODEL}_
"""


def document_adf_pr(
    pipelines: list[ADFPipelineInfo],
    datasets: list[ADFDatasetInfo],
    linked_services: list[ADFLinkedServiceInfo],
    pr_title: str,
    pr_description: str,
) -> str:
    pipeline_details = "\n\n".join(_adf_pipeline_detail(p) for p in pipelines[:10])
    dataset_list = "\n".join(
        f"- `{d.name}` ({d.dataset_type}, linked: `{d.linked_service}`)" for d in datasets
    )
    ls_list = "\n".join(f"- `{ls.name}` ({ls.service_type})" for ls in linked_services)

    user_prompt = f"""Generate documentation for this Azure Data Factory pull request.

**PR Title:** {pr_title}
**PR Description:** {pr_description or "(none provided)"}

**Pipelines Changed:**
{pipeline_details or "(none)"}

**Datasets Changed:**
{dataset_list or "(none)"}

**Linked Services Changed:**
{ls_list or "(none)"}

Write the following sections:
1. **Overview** – what this PR does and why
2. **Pipeline Changes** – for each pipeline, describe activities, control flow, and data movement
3. **Activity Flow Diagram** – embed a Mermaid flowchart for each pipeline showing activity dependencies
4. **Dataset & Connection Changes** – describe any schema or connection changes
5. **Operational Notes** – triggers, schedules, retry policies, monitoring considerations
"""
    ai_doc = _call_claude(
        system_prompt=(
            "You are a senior Azure Data Factory engineer writing technical documentation. "
            "Use Markdown. Include Mermaid diagrams for activity flows."
        ),
        user_prompt=user_prompt,
    )

    static_diagrams = "\n\n".join(
        _pipeline_mermaid(p) for p in pipelines if p.activity_flow
    )
    if static_diagrams:
        ai_doc += f"\n\n## Activity Flow Diagrams (Auto-generated)\n\n{static_diagrams}"

    # End-to-end data lineage — auto-detected from datasets + linked services
    lineage_section = ""
    lineage = _build_adf_lineage(pipelines, datasets, linked_services)
    if lineage.can_build:
        source_note = (
            f"{lineage.source_count} source system(s), "
            if lineage.source_count else ""
        )
        lineage_section = (
            f"\n\n## End-to-End Data Lineage\n\n"
            f"> Auto-generated from {lineage.pipeline_count} pipeline(s) "
            f"({source_note}spanning all storage layers).\n\n"
            f"{lineage.mermaid_code}\n"
        )

    return f"""# PR Documentation: {pr_title}

{ai_doc}
{lineage_section}
---
_Generated by Intelligent Doc Engine | Model: {MODEL}_
"""


def document_function_pr(
    functions: list[FunctionInfo],
    pr_title: str,
    pr_description: str,
) -> str:
    func_details = "\n\n".join(_function_detail(f) for f in functions[:10])

    user_prompt = f"""Generate documentation for this Azure Functions pull request.

**PR Title:** {pr_title}
**PR Description:** {pr_description or "(none provided)"}

**Functions Changed:**
{func_details or "(none)"}

Write the following sections:
1. **Overview** – purpose and impact of this PR
2. **Function Changes** – for each function: purpose, trigger, input/output bindings, key logic
3. **API / Event Contract** – HTTP routes, event schemas, queue names, blob paths
4. **Error Handling & Retry** – any error handling or retry logic added/modified
5. **Dependencies** – external services, environment variables, connection strings referenced
"""
    ai_doc = _call_claude(
        system_prompt=(
            "You are a senior Azure Functions engineer writing technical documentation. "
            "Use Markdown. Be precise about triggers and bindings."
        ),
        user_prompt=user_prompt,
    )

    return f"""# PR Documentation: {pr_title}

{ai_doc}

---
_Generated by Intelligent Doc Engine | Model: {MODEL}_
"""


def document_generic_pr(diff: str, pr_title: str, pr_description: str) -> str:
    text = _call_claude(
        system_prompt="You are a technical writer. Generate Markdown documentation from a PR diff.",
        user_prompt=(
            f"PR Title: {pr_title}\nDescription: {pr_description}\n\nDiff:\n{diff[:4000]}\n\n"
            "Write: Overview, Changes Made, Impact, Notes."
        ),
    )
    return (
        f"# PR Documentation: {pr_title}\n\n"
        f"{text}\n\n"
        f"---\n_Generated by Intelligent Doc Engine_\n"
    )


# ── Helpers ──────────────────────────────────────────────────────────────────

def _sql_file_table(files: list[SQLFileInfo]) -> str:
    rows = ["| File | Layer | Type | Object | Strategy |", "|---|---|---|---|---|"]
    for f in files:
        fname = f.path.replace("\\", "/").split("/")[-1]
        rows.append(
            f"| `{fname}` | {f.layer} | {f.object_type} | `{f.object_name}` | {f.load_strategy} |"
        )
    return "\n".join(rows)


def _column_lineage_section(files: list[SQLFileInfo]) -> str:
    """Build a Markdown column lineage section for files that have column mapping data."""
    sections = []
    for f in files:
        if not f.column_lineage:
            continue
        fname = f.path.replace("\\", "/").split("/")[-1]
        target = str(f.primary_target) if f.primary_target else f.object_name or fname

        rows = ["| Target Column | Source Table | Source Column |", "|---|---|---|"]
        for m in f.column_lineage:
            src_tbl = f"`{m.source_table}`" if m.source_table else "—"
            src_col = f"`{m.source_col}`" if m.source_col else "_(expression)_"
            rows.append(f"| `{m.target_col}` | {src_tbl} | {src_col} |")

        sections.append(f"### `{fname}` → `{target}`\n\n" + "\n".join(rows))

    if not sections:
        return ""
    return "\n## Column Lineage\n\n" + "\n\n".join(sections) + "\n"


def _sql_file_detail(f: SQLFileInfo) -> str:
    targets = ", ".join(f"`{t}`" for t in f.targets) or "_none_"
    sources = ", ".join(f"`{s}`" for s in f.sources[:10]) or "_none_"
    ctes    = ", ".join(f"`{c}`" for c in f.ctes) or "_none_"
    cols    = ", ".join(f"`{c}`" for c in f.columns[:15]) or "_not parsed_"
    fname   = f.path.replace("\\", "/").split("/")[-1]

    snippet = ""
    if f.raw_sql:
        first_lines = "\n".join(f.raw_sql.splitlines()[:30])
        snippet = f"\n```sql\n{first_lines}\n...\n```"

    return f"""### `{fname}`
- **Layer:** {f.layer} | **Type:** {f.object_type} | **Strategy:** {f.load_strategy}
- **Targets:** {targets}
- **Sources:** {sources}
- **CTEs:** {ctes}
- **Columns:** {cols}
{snippet}"""


def _adf_pipeline_detail(p: ADFPipelineInfo) -> str:
    acts = "\n".join(
        f"  - `{a.name}` ({a.activity_type})"
        + (f" → depends on: {a.depends_on}" if a.depends_on else "")
        + (f" | in: {a.inputs}" if a.inputs else "")
        + (f" | out: {a.outputs}" if a.outputs else "")
        for a in p.activities
    )
    return f"""### Pipeline: `{p.name}`
- **Description:** {p.description or "(none)"}
- **Parameters:** {', '.join(p.parameters) or "(none)"}
- **Variables:** {', '.join(p.variables) or "(none)"}
- **Activities ({len(p.activities)}):**
{acts}"""


def _pipeline_mermaid(p: ADFPipelineInfo) -> str:
    if not p.activities:
        return ""
    lines = [f"#### `{p.name}` Activity Flow", "", "```mermaid", "flowchart TD"]
    node_ids = {a.name: f"a{i}" for i, a in enumerate(p.activities)}
    for a in p.activities:
        nid = node_ids[a.name]
        lines.append(f'    {nid}["{a.name}\\n({a.activity_type})"]')
    for src, tgt in p.activity_flow:
        src_id = node_ids.get(src, "")
        tgt_id = node_ids.get(tgt, "")
        if src_id and tgt_id:
            lines.append(f"    {src_id} --> {tgt_id}")
    lines.append("```")
    return "\n".join(lines)


def _function_detail(f: FunctionInfo) -> str:
    bindings_str = "\n".join(
        f"  - `{b.name}` — {b.binding_type} ({b.direction})" for b in f.bindings
    ) or "  (none)"
    http_str = ", ".join(f.http_methods) if f.http_methods else ""
    route_str = f"`{f.route}`" if f.route else ""
    schedule_str = f"`{f.trigger_schedule}`" if f.trigger_schedule else ""
    return f"""### Function: `{f.function_name}` ({f.language})
- **Trigger:** {f.trigger_type} {schedule_str or http_str or ""}
- **Route:** {route_str or "(N/A)"}
- **Auth Level:** {f.auth_level or "(N/A)"}
- **Description:** {f.description or "(none)"}
- **Bindings:**
{bindings_str}"""
